### ISSUE TITLE
Logbook breaks when names of non-existent things (including DLC content when not owned) or Twisted Scavengers are added to the sort list.

### ISSUE THREAD

**Issue by Akiyo06** [prodzpod/MiscModpackUtils#1]
[LogOutput.log](https://github.com/user-attachments/files/17285691/LogOutput.log)

**Comment by prodzpod** [comment]
makes sense, not a bug but maybe ill add a skip as an enhancement

**Comment by Akiyo06** [comment]
That will be very helpful, thanks!
